//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdWorker { get; set; }
        public int IdProduct { get; set; }
        public Nullable<int> Number { get; set; }
        public string Data { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
        public virtual WorkerSet WorkerSet { get; set; }
    }
}
